services:
  dev:
    build:
      context: .
      dockerfile: ../.devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    env_file:
      - ../.devcontainer/.env
    command: sleep infinity